# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
#
jdk:
- openjdk11

## после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
## Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

## Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - youremail@smtp
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
  - CODECOV_TOKEN="b61e8e10-7ce9-47bd-8d8d-bb907eb1f149